add error checking to all posix shell scripts

diff --git a/git/subcommands/git-clean-branches b/git/subcommands/git-clean-branches
--- a/git/subcommands/git-clean-branches
+++ b/git/subcommands/git-clean-branches
@@ -1,15 +1,21 @@
 #!/bin/sh
 
-branches_merged_to_master=$(git branch --merged ${1-master} | grep -v " ${1-master}$")
+# Exit if a command returns a non-zero exit code
+set -o errexit
+
+# Exit if an unset variable is referenced
+set -o nounset
+
+branches_merged_to_master=$(git branch --merged "${1-master}" | grep -v " ${1-master}$")
 
 if [ "$branches_merged_to_master" = "" ]; then
     echo 'No branches to delete'
     return
 fi
 
-echo "The following branches have already been merged to master:\n${branches_merged_to_master}"
+printf "The following branches have already been merged to master:\n%s\n" "$branches_merged_to_master"
 echo "Are these branches ok to delete? (y/n): "
-read response
+read -r response
 if [ "$response" = "y" ]; then
     echo "$branches_merged_to_master" | xargs -r git branch -d
     echo "Branches deleted"
diff --git a/git/subcommands/git-http-to-ssh b/git/subcommands/git-http-to-ssh
--- a/git/subcommands/git-http-to-ssh
+++ b/git/subcommands/git-http-to-ssh
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+# Exit if a command returns a non-zero exit code
+set -o errexit
+
+# Exit if an unset variable is referenced
+set -o nounset
+
 #The if condition is for checking your remote HTTPS URL has `.git` at the end or not
 if git config --get remote.origin.url | grep -P '\.git$' >/dev/null; then
     newURL=`git config --get remote.origin.url | sed -r 's#(http.*://)([^/]+)/(.+)$#git@\2:\3#g'`
diff --git a/git/subcommands/git-r b/git/subcommands/git-r
--- a/git/subcommands/git-r
+++ b/git/subcommands/git-r
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+# Exit if a command returns a non-zero exit code
+set -o errexit
+
+# Exit if an unset variable is referenced
+set -o nounset
+
 if [ $# -eq 0 ]; then
     echo "ERROR: You must provide the number of commits to rebase"
     exit 1
diff --git a/linux/setup b/linux/setup
--- a/linux/setup
+++ b/linux/setup
@@ -1,5 +1,11 @@
 #!/bin/env sh
 
+# Exit if a command returns a non-zero exit code
+set -o errexit
+
+# Exit if an unset variable is referenced
+set -o nounset
+
 # Exit if this OS is not Linux
 if uname | grep -q -i -v linux; then
   exit
